import angular from 'angular';
import 'angular-ui-router'; 
import 'angular-animate';  
import 'angular-touch'  
import 'angular-ui-bootstrap'; 
import 'angular-chart.js';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';

// Import our templates file (generated by Gulp)
import './config/app.templates';

// Import our app functionaity
import './components';
import './services';
import './layout';
import './home';
import './graphs';
import './add-advertisement/';


// Create and bootstrap application
const requires = [
  'ui.router',  
  'ngAnimate',  
  'ngTouch',   
  'ui.bootstrap', 
  'chart.js',
  'templates',
  'app.components',
  'app.services',
  'app.layout',
  'app.home',
  'app.graphs',
  'app.add-advertisement'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.bootstrap(document, ['app'], {
  strictDi: true
});